"""
Product mapping lookup for the middleware.

Loads mapping.json (generated by the Discovery Agent) and provides
fast lookup of Tally stock item names to CATalytics product attributes.

Falls back to the existing regex parser (fetch_products.parse_stock_item_name)
when a product isn't in the mapping.

Usage:
    from mapping_lookup import get_mapping_lookup
    lookup = get_mapping_lookup()  # loads mapping.json once

    result = lookup.classify("Oxygen Gas")
    if result:
        product_master = result["product_master_name"]
        product_type = result["product_type_name"]
        variant = result["variant_master_name"]
        unit = result["unit_master_name"]
    else:
        # Fall back to regex parser
        ...
"""
import json
import logging
import os
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

_DEFAULT_MAPPING_PATH = "mapping.json"
_instance = None


class MappingLookup:
    """In-memory lookup table for Tally → CATalytics product mappings."""

    def __init__(self, mapping_path: str = None):
        self._by_name = {}  # lowercase tally_stock_name → mapping entry
        self._by_guid = {}  # tally_guid → mapping entry
        self._loaded = False
        self._path = mapping_path

        if mapping_path and os.path.exists(mapping_path):
            self.load(mapping_path)

    def load(self, path: str) -> int:
        """Load mapping.json and build lookup indexes."""
        try:
            with open(path, "r", encoding="utf-8") as f:
                data = json.load(f)

            mappings = data.get("mappings", [])
            self._by_name.clear()
            self._by_guid.clear()

            for entry in mappings:
                name = (entry.get("tally_stock_name") or entry.get("stock_item_name", "")).strip()
                if name:
                    self._by_name[name.lower()] = entry

                guid = (entry.get("tally_guid") or "").strip()
                if guid:
                    self._by_guid[guid] = entry

            self._loaded = True
            self._path = path
            logger.info(f"Loaded {len(self._by_name)} product mappings from {path}")
            return len(self._by_name)

        except FileNotFoundError:
            logger.warning(f"Mapping file not found: {path}")
            return 0
        except Exception as e:
            logger.error(f"Failed to load mapping file {path}: {e}")
            return 0

    def classify(self, stock_item_name: str, tally_guid: str = "") -> Optional[dict]:
        """
        Look up a Tally stock item name in the mapping.

        Returns the mapping entry dict if found, or None.
        The returned dict contains:
            product_master_name, product_type_name, product_type_code,
            variant_master_name, variant_name, unit_master_name,
            stock_item_name, hsn_code, igst_rate, cgst_rate, sgst_rate,
            gas_type, grade, asset_type, form, ownership, confidence
        """
        if not self._loaded:
            return None

        # Try GUID first (most reliable)
        if tally_guid:
            entry = self._by_guid.get(tally_guid.strip())
            if entry:
                return entry

        # Then try name (case-insensitive)
        if stock_item_name:
            entry = self._by_name.get(stock_item_name.strip().lower())
            if entry:
                return entry

        return None

    @property
    def is_loaded(self) -> bool:
        return self._loaded

    @property
    def count(self) -> int:
        return len(self._by_name)

    def get_all_names(self) -> list:
        """Return all mapped Tally stock item names."""
        return list(self._by_name.keys())

    def get_unmapped_names(self, tally_names: list) -> list:
        """Return names from the list that aren't in the mapping."""
        return [n for n in tally_names if n.strip().lower() not in self._by_name]


def get_mapping_lookup(path: str = None) -> MappingLookup:
    """
    Get or create the singleton MappingLookup instance.

    Tries these paths in order:
    1. Explicit path argument
    2. MAPPING_FILE env var
    3. mapping.json next to this script
    4. mapping.json in the EXE directory (frozen builds)
    """
    global _instance

    if _instance and _instance.is_loaded and not path:
        return _instance

    if not path:
        path = os.environ.get("MAPPING_FILE", "")

    if not path:
        # Try script directory
        script_dir = Path(__file__).parent
        candidate = script_dir / _DEFAULT_MAPPING_PATH
        if candidate.exists():
            path = str(candidate)

    if not path and getattr(__import__("sys"), "frozen", False):
        # Try EXE directory for frozen builds
        import sys
        exe_dir = Path(sys.executable).parent
        candidate = exe_dir / _DEFAULT_MAPPING_PATH
        if candidate.exists():
            path = str(candidate)

    _instance = MappingLookup(path)
    return _instance
